### ISSUE TITLE
Special need: YAF with child needs child bed near YAF space

### ISSUE THREAD

**Issue by brylie** [quaker-io/pym-2015#49]
> The requested sentence, “YAF parent of young children, in separate dorm, but wants to be near YAF community space,” isn’t in the online form.  We need to know this to assign beds. --Margaret Mossman
## User stories

As a YAF with child
I need my child to stay in a dorm near the YAF community space
so that I can be near my child during the event

As a registrar
I need to know when YAFs have children needing nearby dorm space
so that we can assign them a bed near the YAF space

**Comment by styrrell** [comment]
Hi Brylie, sorry, this is wrong. A child (under 18) must always be housed
with parent or sponsor, unless they are old enough to be in the JYM space.

The intent here is for YAFs who have children, and do not want to sleep in
the YAF dorm, to indicate that they (their family) would like to be housed
near the YAF dorm:

User stories

As a YAF with child
I need to stay in a dorm near the YAF community space
so that I can be near my child during the event

As a registrar
I need to know when YAFs with children need nearby dorm space
so that we can assign them a bed near the YAF space
Joyce, Joe, Margaret, do you agree?

Do you get these notifications from Git?

 ;Sarah

**Comment by brylie** [comment]
OK, this still seems ambiguous. Lets try to narrow down these user stories with very specific wording.

User Stories

```
As a YAF with child
I need to stay with my child in a dorm near the YAF community space
so that my family is near the YAF space during the event
```

```
As a registrar
I need to know when YAFs with children need dorm accommodations near the YAF space
so that I can assign them proper accommodations
```

**Comment by brylie** [comment]
Also, as an idea for a solution, might the special needs field be used for this user story? E.g. we can add help text below the special needs field describing examples of special needs:

> Special needs include accessibility needs, family accommodations near people or groups such as JYM/YAF, etc.

**Comment by brylie** [comment]
At this point it is much easier to add help text on existing fields than to add more form fields, conditional logic, etc.

**Comment by styrrell** [comment]
Sorry, I can read Git but can't write to it. Putting it in special needs along with a prompt seems ok. "Tell us anything special we need to know: mobility issues, loud snorer, travel needs, desire to be near YAF community space, etc."
There may be others who want to be near some program or person. YAFs were just the ones who asked.  Or isn't there a place to designate specific roommate?  It could be there.

**Comment by brylie** [comment]
> Tell us anything special we need to know: mobility issues, loud snorer, travel needs, desire to be near YAF community space, etc.

I have added the special needs help text.

@styrrell make sure to sign in to Github in order to comment.
